# This is a quickstart docker compose file that 
version: '3'
services:
  mysql:
    # need to support arm64 so need Oracle
    image: mysql:8.0.34-oracle
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: tools
      MYSQL_PASSWORD: tools
      MYSQL_DATABASE: tools
    command:
     - --character-set-server=UTF8MB4
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 500ms
      timeout: 1s
      retries: 30
  app:
    # The prebuilt image
    image: ghcr.io/oxctl/tool-support:latest
    environment:
      # This is so that we use the prebuilt image
      SPRING_PROFILES_ACTIVE: docker,ssl
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    depends_on:
      mysql:
        condition: service_healthy
    
