language: java
jdk:
  - openjdk11
branches:
  only:
    - master
build:
  cache: true
  cache_dir_list:
    - ~/.m2
  ci:
    - mvn install -DskipTests=true
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - mvn test
    - cp -r target/surefire-reports shippable/testresults
  post_ci:
    - if [ "$IS_PULL_REQUEST" == false ]; then mvn -Djib.tag=${BRANCH}.${BUILD_NUMBER} pl.project13.maven:git-commit-id-plugin:revision jib:build; fi
    - if [ "$IS_PULL_REQUEST" == false ]; then shipctl post_resource_state_multi "canvas-proxy-image" "sourceName=211318693510.dkr.ecr.eu-west-1.amazonaws.com/ctl/canvas-proxy versionName=$BRANCH.$BUILD_NUMBER"; fi

integrations:
  hub:
    - integrationName: AWS
      region: eu-west-1
      type: ecr
  notifications:
    - integrationName: email
      type: email
      recipients:
        - matthew.buckett@ctl.ox.ac.uk
      on_success: change
      on_failure: change
      on_cancel: change
      on_start: never
      on_pull_request: never

resources:
  - name: canvas-proxy-image
    type: image
    integration: AWS
    versionTemplate:
      sourceName: "211318693510.dkr.ecr.eu-west-1.amazonaws.com/ctl/canvas-proxy"
      versionName: "latest"
  - name: aws-config
    type: cliConfig
    integration: AWS
    pointer:
      region: eu-west-1
  - name: canvas-proxy-env-params-dev
    type: params
    version:
      params:
        PORT: 8080
        AWS_EB_ENVIRONMENT: "canvas-oauth-proxy-dev-env"
        AWS_EB_APPLICATION: "canvas-oauth-proxy"
  - name: canvas-proxy-env-params-prod
    type: params
    version:
      params:
        AWS_EB_ENVIRONMENT: "canvas-oauth-proxy-prod-env"

  - name: canvas-proxy-repo
    type: gitRepo
    integration: github
    pointer:
      sourceName: oxctl/canvas-proxy
      branch: master

jobs:
  - name: canvas-proxy_runCI
    type: runCI
    flags:
      - canvas-proxy
    steps:
      - OUT: canvas-proxy-image

  - name: canvas-proxy-deploy-dev
    type: runSh
    steps:
      - IN: canvas-proxy-image
      - IN: aws-config
        switch: off
      - IN: canvas-proxy-env-params-dev
        switch: off
      - IN: canvas-proxy-repo
        switch: off
      - TASK:
          - script: export
          - script: aws elasticbeanstalk describe-applications
          - script: pushd $CANVASPROXYREPO_STATE/elasticbeanstalk && ls -al
          - script: export IMAGE="${CANVASPROXYIMAGE_SOURCENAME}:${CANVASPROXYIMAGE_VERSIONNAME}"
          - script: shippable_replace Dockerrun.aws.json .elasticbeanstalk/config.yml
          - script: eb deploy -v -l "shippable.canvas-proxy.${CANVASPROXYIMAGE_VERSIONNAME}" -m "${CANVASPROXYREPO_COMMIT_MESSAGE}"
          # Save the image that we are currently running
          - script: shipctl put_resource_state $JOB_NAME version "shippable.canvas-proxy.${CANVASPROXYIMAGE_VERSIONNAME}"

  # This just takes the image that is currently on the dev instance and deploys it to the production environment
  - name: canvas-proxy-deploy-prod
    type: runSh
    steps:
      - IN: canvas-proxy-deploy-dev
        switch: off
      - IN: aws-config
        switch: off
      - IN: canvas-proxy-env-params-dev
        switch: off
      - IN: canvas-proxy-env-params-prod
        switch: off
      - IN: canvas-proxy-repo
        switch: off
      - TASK:
          - script: aws elasticbeanstalk describe-applications
          - script: pushd $CANVASPROXYREPO_STATE/elasticbeanstalk && ls -al
          - script: shippable_replace .elasticbeanstalk/config.yml
          - script: version="$(shipctl get_resource_version_key canvas-proxy-deploy-dev version)"
          - script: eb deploy -v -l "${version}"
