# These are used to validate the JWK when we are not signing tokens ourselves (both proxy and lti).
# This allows JWTs issued by any of the Instructure instances to access the application
jwt.issuer.live.issuer=https://canvas.instructure.com
jwt.issuer.live.jwksUrl=https://sso.canvaslms.com/api/lti/security/jwks
jwt.issuer.test.issuer=https://canvas.test.instructure.com
jwt.issuer.test.jwksUrl=https://sso.test.canvaslms.com/api/lti/security/jwks
jwt.issuer.beta.issuer=https://canvas.beta.instructure.com
jwt.issuer.beta.jwksUrl=https://sso.beta.canvaslms.com/api/lti/security/jwks

# The fallback URLs for the CSS/JSON
spring.application.name=Canvas Tools
canvas.common.css=https://du11hjcvx0uqb.cloudfront.net/dist/brandable_css/new_styles_normal_contrast/bundles/common-1638e73116.css
canvas.brand.json=https://du11hjcvx0uqb.cloudfront.net/dist/brandable_css/83323f307b8aa57724b3129e9742c6e2/variables-750d72b9d3e5d522f965bf904110c132.json

# After Spring Boot 2.3 messages aren't included in the error response by default.
# This reverts to the older behaviour
server.error.include-message=always

# We don't have any real pages to reload and if we leave it enabled Spring Boot applications error when
# they can't access to the livereload port
spring.devtools.livereload.enabled=false

# This is needed so that we can load lazy entities when serialising JSON.
spring.jpa.open-in-view=true

# Setup sentry configuration
sentry.logging.minimum-event-level=warn
sentry.send-default-pii=true
# Enable tracking for sentry
sentry.traces-sample-rate=0.2
# set @Order to be higher than custom exception handlers
sentry.exception-resolver-order=2

# With the configuration being stored in the DB we need to make sure we cache the lookups
# so that we don't end up hitting the database hard for requests.
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.javax.cache.missing_cache_strategy=create

# exceptions we don't want sent to Sentry
sentry.ignored-exceptions-for-type=\
  org.apache.catalina.connector.ClientAbortException,\
  org.springframework.http.InvalidMediaTypeException,\
  org.springframework.util.InvalidMimeTypeException,\
  org.springframework.security.web.firewall.RequestRejectedException,\
  org.springframework.web.multipart.MultipartException,\
  org.springframework.security.oauth2.client.ClientAuthorizationRequiredException

logging.level.org.springframework.web.servlet.resource.ResourceHttpRequestHandler=error

spring.security.user.roles=admin

# expose actuator component endpoints (db, diskSpace, mail, ping)
management.endpoint.health.show-components=always

# Our outbound requests aren't well tagged and this results in the metrics service
# being unable to group them correctly, so we disabled the metrics.
management.metrics.web.client.request.autotime.enabled=false