# These are used to validate the JWK.
# This allows JWTs issued by any of the Instructure instances to access the application
jwt.issuer.live.issuer=https://canvas.instructure.com
jwt.issuer.live.jwksUrl=https://canvas.instructure.com/api/lti/security/jwks
jwt.issuer.test.issuer=https://canvas.test.instructure.com
jwt.issuer.test.jwksUrl=https://canvas.test.instructure.com/api/lti/security/jwks
jwt.issuer.beta.issuer=https://canvas.beta.instructure.com
jwt.issuer.beta.jwksUrl=https://canvas.beta.instructure.com/api/lti/security/jwks

# The fallback URLs for the CSS/JSON
spring.application.name=Canvas Proxy
canvas.common.css=https://du11hjcvx0uqb.cloudfront.net/dist/brandable_css/new_styles_normal_contrast/bundles/common-1638e73116.css
canvas.brand.json=https://du11hjcvx0uqb.cloudfront.net/dist/brandable_css/83323f307b8aa57724b3129e9742c6e2/variables-750d72b9d3e5d522f965bf904110c132.json

# We don't have any real pages to reload and if we leave it enabled Spring Boot applications error when
# they can't access to the livereload port
spring.devtools.livereload.enabled=false

# We don't want the transaction to be open the whole time.
spring.jpa.open-in-view=false

# We only want to use cookies for this bit where the user grants the proxy access to their account.
# If we have the cookie valid for everywhere then after granting access it gets used for the token refresh and this
# means that we don't get a unauthorized error, but instead get redirected.
server.servlet.session.cookie.path=/token/check

# Setup sentry configuration
sentry.logging.minimum-event-level=warn
sentry.send-default-pii=true
# Enable tracking for sentry
sentry.enable-tracing=true
sentry.traces-sample-rate=0.2



