# This profile is for running in AWS and using the AWS Secrets Manager JDBC driver.
spring.datasource.driver-class-name=com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver

# Config for AWS EB
spring.datasource.url=${SECRET_RDS}
spring.datasource.username=${SECRET_RDS}
spring.jpa.hibernate.ddl-auto=update

# Make sure we use UTF-8
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# Disable dev stuff
spring.devtools.add-properties=false

# Force the cookie to be only supplied on HTTPS connections (always the case on AWS)
server.servlet.session.cookie.secure=true

# As we are proxying through nginx
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto