---
AWSTemplateFormatVersion: '2010-09-09'
Metadata: {}
Description: "Creates resources for a given app, in a given region"

Parameters:
  orgName:
    Description: "Name of organization - used in naming"
    Type: String
    Default: "cad"
  accountType:
    Type: "String"
    Description: "production or non-production account?"
    AllowedValues:
      - "prod"
      - "nonprod"
  appName:
    Description: "The app's name"
    Type: String
  envType:
    Description: "The env type: prod, beta, test, etc"
    Type: String
    AllowedValues:
      - "prod"
      - "beta"
      - "test"
      - "staging"
  drRegion:
    Type: String
    Default: "eu-central-1"
  #should we setup bounce handling for this domain
  handleBounces:
    Description: "The env type: prod, beta, test, etc"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"


Conditions:
  isProdEnv: {"Fn::Equals": [!Ref envType, "prod"]}
  isProdAccount: {"Fn::Equals": [!Ref accountType, "prod"]}
  setupBounce: {"Fn::Equals": [!Ref handleBounces, "Yes"]}
  #isProdRegion: {"Fn::Equals" : [!Ref "AWS::Region", 'eu-west-1']}
  #isDRRegion: {"Fn::Equals" : [!Ref "AWS::Region", 'eu-central-1']}


Resources:


  # Configure more for bounce-handling whenw we have decided
  sesRuleSet:
    Condition: setupBounce
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Sub  "${appName}-${accountType}-ruleset"

  ## Configure how bounce handling will be managed
  ##ToDo: create bounce hamdling resources for apps that need it

  ebApplication:
    Type: "AWS::ElasticBeanstalk::Application"
    Properties:
      ApplicationName: !Sub "${appName}"
      ResourceLifecycleConfig:
        ServiceRole: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/aws-elasticbeanstalk-service-role"   #aws-elasticbeanstalk-service-role"
        VersionLifecycleConfig:
          MaxAgeRule:
            Enabled: true
            MaxAgeInDays: 90
            DeleteSourceFromS3: true


Outputs:
  appName:
    Description: "The EB Application Name"
    Value: !Ref ebApplication
    Export:
      Name: !Sub "${appName}-${envType}-ebapp"
