# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Backend
run-name: "Deploy ${{ github.ref }}"

on:
  push:
    branches: [ 'master', 'release', 'dr-*' ]

jobs:
  aws-params:
    # This attempts to parse the AWS parameters file and load it into JSON that's usable in GitHib Actions.
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    # This is needed for AWS assume role
    outputs:
      json: ${{ steps.parse.outputs.json }}
    steps:
      - uses: actions/checkout@v4
      - id: parse
        run: |
          PARAMS=$(jq 'map(split("=")|  { (.[0]|tostring): .[1]} ) | add'  < ./aws/${{ (startsWith(github.ref_name, 'dr-')) && 'dr' || github.ref_name }}.json)
          echo json=${PARAMS} | tee -a $GITHUB_OUTPUT

  call-build-and-deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    needs: [ aws-params ]
    with:
      account_type: ${{ fromJSON(needs.aws-params.outputs.json).accountType }}
      app_name: ${{ fromJSON(needs.aws-params.outputs.json).appName }}
      aws_account_id: ${{ fromJSON(needs.aws-params.outputs.json).awsAccountId }}
      aws_parameters: ${{ (startsWith(github.ref_name, 'dr-')) && 'dr' || github.ref_name }}
      aws_region: ${{ fromJSON(needs.aws-params.outputs.json).awsRegion }}
      do_deploy: ${{ (fromJSON(needs.aws-params.outputs.json).envType == 'prod') && true || github.ref_name == github.event.repository.default_branch }}
      env_type: ${{ fromJSON(needs.aws-params.outputs.json).envType }}
      github_env: ${{ fromJSON(needs.aws-params.outputs.json).envType }}
      ref: ${{ github.ref }}
      sha: ${{ github.sha }}
    secrets: inherit